apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: k8s-trial
    role: master
    tier: backend
spec:
                              # 省略されているけどtypeはデフォルトの"ClusterIP"。クラスタ上の内部IPアドレスにServiceを公開
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: k8s-trial
    role: master
    tier: backend